version: '3.9'

services:
  app:
    build: .
    container_name: nodetest
    ports: 
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
      - PORT-3000
