version: '3.9'

services:
  app:
    build: .
    image: omsharma108/basics-node
    ports: 
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      - NODE_ENV=development
      - PORT-3000
